# Generated by Django 5.2.5 on 2026-02-09 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_size', models.CharField()),
                ('default_metric', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('EU', 'Europe'), ('US', 'USA')], max_length=2)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('kcal_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('protein_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('fat_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('carbohydrates_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('salt_1g', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('packaging_size', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('packaging_metric', models.CharField(max_length=10)),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.packaging')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='diet.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='diet.product')),
            ],
        ),
    ]
