# Generated by Django 5.2.5 on 2026-08-05 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('default_size', models.CharField()),
                ('default_metric', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe', models.JSONField(blank=True, default=dict, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='dishes_images/')),
                ('additional_allergens', models.ManyToManyField(related_name='dishes', to='diet.allergen')),
                ('diet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.diettype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.dishcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_type', models.CharField(choices=[('EU', 'Europe'), ('US', 'USA')], max_length=2)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('kcal_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('protein_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('fat_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('carbohydrates_1g', models.DecimalField(decimal_places=5, max_digits=12)),
                ('salt_1g', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('packaging_size', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('packaging_metric', models.CharField(max_length=10)),
                ('barcode', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/')),
                ('allergens', models.ManyToManyField(related_name='products', to='diet.allergen')),
                ('packaging_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.packaging')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='diet.productcategory')),
                ('countries', models.ManyToManyField(related_name='products', to='diet.productcountry')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_packaging', models.CharField(blank=True, default=None, null=True)),
                ('ammount', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('weight_in_g', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='diet.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.product')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ManyToManyField(related_name='dishes', through='diet.DishIngredient', to='diet.product'),
        ),
    ]
