# Generated by Django 5.2.5 on 2026-02-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='product',
        ),
        migrations.AddField(
            model_name='allergen',
            name='product',
            field=models.ManyToManyField(related_name='allergens', to='diet.product'),
        ),
    ]
