# Generated by Django 5.2.5 on 2026-02-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_productcountry_remove_allergen_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='allergen',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.ManyToManyField(related_name='products', to='diet.productcountry'),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(related_name='products', to='diet.allergen'),
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe', models.JSONField(default=dict)),
                ('img', models.ImageField(blank=True, null=True, upload_to='dishes_images/')),
                ('additional_allergens', models.ManyToManyField(related_name='dishes', to='diet.allergen')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diet_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.diettype')),
                ('product', models.ManyToManyField(related_name='dishes', to='diet.product')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.dishcategory')),
            ],
        ),
    ]
