# Generated by Django 5.2.5 on 2026-08-13 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_diettype_name_de_diettype_name_en_diettype_name_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diettype',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='diettype',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='diettype',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='diettype',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='diettype',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='dishcategory',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='amount_g',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='packaging_size',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='packaging_type',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='packaging',
            name='name_pl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.RemoveField(
            model_name='product',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_metric',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packaging_type',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name_pl',
        ),
        migrations.AddField(
            model_name='mealitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Ilość porcji, np. 2 dla 2 plastrów lub 150 dla 150g', max_digits=8),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='calculated_gram_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wyliczona końcowa waga w gramach', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name_de',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name_en',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name_es',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name_fr',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_name_pl',
            field=models.CharField(blank=True, help_text='np. Puszka, Kubek, Paczka, Butelka', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='package_whole_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Waga całego opakowania w gramach/ml', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_1g',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_1g',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='kcal_1g',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein_1g',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_1g',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FullMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('portion', models.FloatField()),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullmeal', to='diet.mealcategory')),
            ],
        ),
        migrations.AddField(
            model_name='mealitem',
            name='full_meal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='diet.fullmeal'),
        ),
        migrations.CreateModel(
            name='ProductServingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(choices=[('g', 'Gram'), ('ml', 'Mililitr'), ('piece', 'Sztuka'), ('slice', 'Plaster'), ('cup', 'Szklanka / Kubek'), ('tbsp', 'Łyżka'), ('tsp', 'Łyżeczka'), ('can', 'Puszka'), ('pack', 'Opakowanie / Paczka'), ('handful', 'Garść'), ('serving', 'Porcja producenta'), ('custom', 'Własna miara')], max_length=20)),
                ('custom_label', models.CharField(blank=True, help_text='np. Duża łyżka, Szklanka 250ml', max_length=100, null=True)),
                ('gram_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_global', models.BooleanField(default=True, help_text='True jeśli miara wygenerowana przez AI/System, False jeśli stworzona przez konkretnego usera')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_units', to='diet.product')),
            ],
        ),
        migrations.AddField(
            model_name='mealitem',
            name='product_serving_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.productservingunit'),
        ),
    ]
