# Generated by Django 5.2.5 on 2026-08-18 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_remove_diettype_name_de_remove_diettype_name_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAdditionalInfo',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='additional_info', serialize=False, to='diet.product')),
                ('is_vegan', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_vegetarian', models.BooleanField(blank=True, db_index=True, null=True)),
                ('is_palm_oil_free', models.BooleanField(blank=True, null=True)),
                ('is_complete_profile', models.BooleanField(default=True, help_text='True jeśli produkt ma kompletne dane o cukrach i tłuszczach nasyconych')),
                ('ingredients_text', models.TextField(blank=True, null=True)),
                ('traces', models.JSONField(blank=True, default=list, help_text="Śladowe ilości: ['soybeans', 'gluten']")),
                ('labels', models.JSONField(blank=True, default=list, help_text="Certyfikaty: ['bio', 'no-gluten', 'organic']")),
                ('additives_tags', models.JSONField(blank=True, default=list, help_text="Lista dodatków E: ['e322', 'e330']")),
            ],
        ),
        migrations.RemoveField(
            model_name='dish',
            name='additional_allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text="np. ['milk', 'nuts']"),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, help_text='np. Piątnica, Bovetti', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='countries',
            field=models.JSONField(blank=True, default=list, help_text="Kraje dystrybucji: ['poland', 'germany']"),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_1g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link do miniatury z CDN', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nova_group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_index=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_display',
            field=models.CharField(blank=True, help_text="Oryginalny tekst z etykiety np. '350 g', '4 x 125g'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_1g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_1g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='EAN-13, EAN-8, UPC', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='diet.productcategory'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='diet_produc_barcode_26a834_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'brand'], name='diet_produc_title_4e051f_idx'),
        ),
        migrations.DeleteModel(
            name='Allergen',
        ),
    ]
