# Generated by Django 5.2.5 on 2026-02-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_diettype_dishcategory_remove_allergen_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='allergens',
        ),
    ]
