# Generated by Django 5.2.5 on 2026-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_rename_product_product_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
