# Generated by Django 5.2.5 on 2026-08-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_productadditionalinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='meal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Śniadanie'), (2, 'Drugie śniadanie'), (3, 'Obiad'), (4, 'Podwieczorek'), (5, 'Kolacja'), (6, 'Custom')], default=1),
        ),
        migrations.AlterField(
            model_name='mealcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
