# Generated by Django 5.2.5 on 2026-08-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_mealcategory_meal_type_alter_mealcategory_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='diet_produc_barcode_26a834_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='diet_produc_title_4e051f_idx',
        ),
    ]
