# Generated by Django 5.2.5 on 2026-02-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_dish_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='additional_allergens',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='diet_type',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='img',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='product',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='recipe',
        ),
        migrations.CreateModel(
            name='ProductMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('weight_in_g', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='diet.packaging')),
            ],
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='diet.dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.product')),
                ('product_measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.productmeasure')),
            ],
        ),
    ]
