# Generated by Django 5.2.5 on 2026-02-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_remove_dish_additional_allergens_remove_dish_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='additional_allergens',
            field=models.ManyToManyField(related_name='dishes', to='diet.allergen'),
        ),
        migrations.AddField(
            model_name='dish',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.dishcategory'),
        ),
        migrations.AddField(
            model_name='dish',
            name='diet_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diet.diettype'),
        ),
        migrations.AddField(
            model_name='dish',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='dishes_images/'),
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='product',
            field=models.ManyToManyField(related_name='dishes', through='diet.DishIngredient', to='diet.product'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
