# Generated by Django 5.2.5 on 2026-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_dish_additional_allergens_dish_author_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
