# Generated by Django 5.2.5 on 2026-08-23 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_product_diet_produc_barcode_26a834_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productservingunit',
            index=models.Index(fields=['product', 'id'], name='diet_produc_product_a2e229_idx'),
        ),
    ]
