# Generated by Django 5.2.5 on 2026-08-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_productservingunit_diet_produc_product_a2e229_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
