# Generated by Django 5.2.5 on 2026-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_alter_dish_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredient',
            name='product_measure',
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ammount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='name_packaging',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='weight_in_g',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductMeasure',
        ),
    ]
