# Generated by Django 5.2.5 on 2026-02-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0009_remove_dishingredient_product_measure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='author',
            new_name='user',
        ),
    ]
