# Generated by Django 5.2.5 on 2026-08-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0011_setup_fts_unaccent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='diet_produc_title_4e051f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_user_title_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_title_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='prod_brand_trgm_idx',
        ),
    ]
