# Generated by Django 5.2.5 on 2026-08-24 16:52

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0012_remove_product_diet_produc_title_4e051f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='product_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
