# Generated by Django 5.2.5 on 2026-08-27 08:54

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0013_product_product_title_trgm_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_title_trgm_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(condition=models.Q(('user__isnull', True)), fields=['title'], name='product_title_trgm_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
