# Generated by Django 5.2.5 on 2026-08-27 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0014_remove_product_product_title_trgm_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, default='pl', max_length=10)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='diet.product')),
            ],
            options={
                'unique_together': {('product', 'language')},
            },
        ),
    ]
