# Generated by Django 5.2.5 on 2026-09-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0015_productdescription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productdescription',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='productdescription',
            index=models.Index(fields=['product', 'language'], name='diet_produc_product_ac411b_idx'),
        ),
    ]
