# Generated by Django 5.2.5 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0016_alter_productdescription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealcalendar',
            name='water_intake_ml',
            field=models.PositiveIntegerField(default=0, help_text='Ilość wypitej wody w ml dla danego dnia'),
        ),
    ]
