# Generated by Django 5.2.5 on 2025-09-22 15:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('date_time_event', models.DateTimeField()),
                ('duration_min', models.PositiveIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=255)),
                ('flat_number', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.category')),
            ],
        ),
        migrations.CreateModel(
            name='EventAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advanced_level', models.CharField(choices=[('none', 'None'), ('begginer', 'Begginer'), ('semi-advanced', 'Semi-advanced'), ('advanced', 'Advanced'), ('all', 'All')], default='none', max_length=255)),
                ('places_for_people_limit', models.PositiveIntegerField()),
                ('age_limit', models.CharField(choices=[('<12', '<12'), ('12 - 16', '12 - 16')], max_length=255)),
                ('participant_list_show', models.BooleanField(default=False)),
                ('public_event', models.BooleanField(default=True)),
                ('free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('payment_in_app', models.BooleanField(default=False)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='event.event')),
            ],
        ),
    ]
