# Generated by Django 5.2.5 on 2025-10-02 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialGuests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('add_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_guests', to='event.eventadditionalinfo')),
            ],
        ),
    ]
