# Generated by Django 5.2.5 on 2025-10-02 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_specialguests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventadditionalinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
