# Generated by Django 5.2.5 on 2025-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventinvitation_eventparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadditionalinfo',
            name='public_event',
        ),
        migrations.AddField(
            model_name='event',
            name='public_event',
            field=models.BooleanField(default=True),
        ),
    ]
