# Generated by Django 5.2.5 on 2025-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventinvitation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitation',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventadditionalinfo',
            name='age_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
