# Generated by Django 5.2.5 on 2025-10-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_rename_presense_eventparticipant_presence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventadditionalinfo',
            name='participant_list_show',
        ),
    ]
