# Generated by Django 5.2.5 on 2025-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_eventadditionalinfo_participant_list_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialguests',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialguests',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialguests',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
