# Generated by Django 5.2.5 on 2026-01-13 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_specialguests_nickname_alter_specialguests_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinvitation',
            name='date_added',
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
