# Generated by Django 5.2.5 on 2026-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_eventinvitation_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvitation',
            name='code',
            field=models.CharField(db_index=True, max_length=8, unique=True),
        ),
    ]
