# Generated by Django 5.2.5 on 2026-01-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_profile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('specializations', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainerprofile', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=2000)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CertyficationTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('identyficatior', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_date', models.DateField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certyficates', to='user_profile.trainerprofile')),
            ],
        ),
    ]
