# Generated by Django 5.2.5 on 2026-01-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
