# Generated by Django 5.2.5 on 2026-01-19 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_trainerpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='certyficationtrainer',
            name='additional_fields',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CertificationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cert_photos/')),
                ('certyficat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_profile.certyficationtrainer')),
            ],
        ),
    ]
