# Generated by Django 5.2.5 on 2026-01-19 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_trainerobservation_trainerrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerobservation',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user_profile.trainerprofile'),
        ),
    ]
