# Generated by Django 5.2.5 on 2026-01-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_trainerobservation_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='phone_business',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
