# Generated by Django 5.2.5 on 2026-01-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_trainerprofile_business_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='img_profile/'),
        ),
    ]
