# Generated by Django 5.2.5 on 2026-01-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_trainerprofile_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='pick_specialization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
