# Generated by Django 5.2.5 on 2026-01-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_trainerprofile_pick_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotosCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoscollections', to='user_profile.trainerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='trainer_collection_photos/')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='user_profile.photoscollection')),
            ],
        ),
    ]
