# Generated by Django 5.2.5 on 2026-01-29 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_photoscollection_trainerimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
