# Generated by Django 5.2.5 on 2026-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_trainerimages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
