# Generated by Django 5.2.5 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_userprofile_city_userprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_water_goal_ml',
            field=models.PositiveIntegerField(default=2000, help_text='Dzienny cel nawodnienia w ml'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='standard_water_intake_ml',
            field=models.PositiveIntegerField(default=250, help_text='Standardowa porcja wody w ml (np. szklanka)'),
        ),
    ]
