# Generated by Django 5.2.5 on 2025-08-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_centraluser_is_user_activated_twofactory'),
    ]

    operations = [
        migrations.AddField(
            model_name='centraluser',
            name='first_name',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centraluser',
            name='last_name',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centraluser',
            name='phone_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
